insert into company (name, email, phone, address, url, type, id) values ('Blognation', 'iarchard0@skype.com', '278-268-2241', '30 Gale Circle', 'java.com', 'technology', 1);
insert into company (name, email, phone, address, url, type, id) values ('Vidoo', 'mworld1@marriott.com', '720-711-7335', '86362 Lien Court', 'ted.com', 'healthcare', 2);
insert into company (name, email, phone, address, url, type, id) values ('Youspan', 'dvasenin2@naver.com', '361-532-9264', '78404 Porter Alley', 'rakuten.co.jp', 'technology', 3);
insert into company (name, email, phone, address, url, type, id) values ('Tanoodle', 'cklemps3@ftc.gov', '872-243-8672', '7548 High Crossing Court', 'wix.com', 'finance', 4);
insert into company (name, email, phone, address, url, type, id) values ('Tavu', 'ezanicchi4@ft.com', '736-892-3296', '819 Elgar Park', 'jugem.jp', 'healthcare', 5);
insert into company (name, email, phone, address, url, type, id) values ('Gigaclub', 'fbogart5@nifty.com', '166-234-7220', '979 Mifflin Pass', 'reverbnation.com', 'healthcare', 6);
insert into company (name, email, phone, address, url, type, id) values ('Oyoloo', 'lkenwood6@trellian.com', '754-742-6486', '2 Tennessee Place', 'fc2.com', 'manufacturing', 7);
insert into company (name, email, phone, address, url, type, id) values ('Rhycero', 'balphonso7@amazon.com', '964-811-7117', '28834 Wayridge Pass', 'sina.com.cn', 'finance', 8);
insert into company (name, email, phone, address, url, type, id) values ('Wikibox', 'tcasaroli8@usatoday.com', '579-693-8532', '09 Elka Crossing', 'liveinternet.ru', 'healthcare', 9);
insert into company (name, email, phone, address, url, type, id) values ('Jaxbean', 'fplaid9@opensource.org', '412-601-4741', '45101 Bonner Street', 'smugmug.com', 'retail', 10);
insert into company (name, email, phone, address, url, type, id) values ('Kaymbo', 'amacglorya@dmoz.org', '479-388-9451', '0463 Dahle Parkway', 'forbes.com', 'finance', 11);
insert into company (name, email, phone, address, url, type, id) values ('Photojam', 'bmcianb@nasa.gov', '971-428-0835', '0242 Pankratz Avenue', 'ezinearticles.com', 'retail', 12);
insert into company (name, email, phone, address, url, type, id) values ('Dabshots', 'gpittendreighc@merriam-webster.com', '209-650-5552', '70233 Nobel Court', 'topsy.com', 'retail', 13);
insert into company (name, email, phone, address, url, type, id) values ('Yozio', 'bpercevald@auda.org.au', '745-859-2096', '27 Grover Court', 'angelfire.com', 'finance', 14);
insert into company (name, email, phone, address, url, type, id) values ('Blogtag', 'fasline@gnu.org', '250-661-0571', '42 Fuller Junction', 'theglobeandmail.com', 'finance', 15);
insert into company (name, email, phone, address, url, type, id) values ('Vipe', 'mcadaganf@npr.org', '327-572-3113', '4352 Manitowish Drive', 'seesaa.net', 'technology', 16);
insert into company (name, email, phone, address, url, type, id) values ('Trupe', 'mhurleyg@usgs.gov', '109-445-4886', '8 Stuart Lane', 'ning.com', 'technology', 17);
insert into company (name, email, phone, address, url, type, id) values ('Brainsphere', 'cboswardh@time.com', '880-503-7502', '0382 Dexter Lane', 'drupal.org', 'finance', 18);
insert into company (name, email, phone, address, url, type, id) values ('Gabcube', 'twiersmai@techcrunch.com', '309-289-9058', '72215 Miller Parkway', 'omniture.com', 'technology', 19);
insert into company (name, email, phone, address, url, type, id) values ('Linkbridge', 'tmetherellj@opera.com', '438-789-1865', '61256 Hoepker Street', 'scribd.com', 'healthcare', 20);
insert into company (name, email, phone, address, url, type, id) values ('Feedmix', 'cgilphillank@cpanel.net', '853-862-2891', '655 Sutherland Avenue', 'facebook.com', 'healthcare', 21);
insert into company (name, email, phone, address, url, type, id) values ('Rhybox', 'crendelll@loc.gov', '997-257-5114', '5 Pierstorff Alley', 'google.it', 'technology', 22);
insert into company (name, email, phone, address, url, type, id) values ('JumpXS', 'estaffm@amazonaws.com', '959-247-5166', '10008 6th Terrace', 'nba.com', 'finance', 23);
insert into company (name, email, phone, address, url, type, id) values ('Voonix', 'sdeavesn@blinklist.com', '304-524-6960', '14237 Cambridge Street', 'miibeian.gov.cn', 'manufacturing', 24);
insert into company (name, email, phone, address, url, type, id) values ('Pixonyx', 'zfrankisso@jiathis.com', '362-357-0850', '3824 Algoma Center', 'msn.com', 'technology', 25);
insert into company (name, email, phone, address, url, type, id) values ('Eare', 'dbourgesp@multiply.com', '741-580-5201', '31157 Northwestern Drive', 'webs.com', 'healthcare', 26);
insert into company (name, email, phone, address, url, type, id) values ('Realmix', 'ewhithornq@bandcamp.com', '996-817-0976', '101 Kipling Pass', 'bing.com', 'finance', 27);
insert into company (name, email, phone, address, url, type, id) values ('Lajo', 'hcarhartr@whitehouse.gov', '507-853-9664', '488 Katie Terrace', 'hhs.gov', 'technology', 28);
insert into company (name, email, phone, address, url, type, id) values ('Rhyzio', 'lfosberrys@baidu.com', '301-932-6631', '4 Springs Center', 'wikia.com', 'manufacturing', 29);
insert into company (name, email, phone, address, url, type, id) values ('Tambee', 'tbendittt@cornell.edu', '110-827-3838', '83594 Sutherland Terrace', 'icio.us', 'finance', 30);
insert into company (name, email, phone, address, url, type, id) values ('Yodoo', 'csieneu@exblog.jp', '932-279-3421', '922 Nancy Center', 'istockphoto.com', 'healthcare', 31);
insert into company (name, email, phone, address, url, type, id) values ('Oyoba', 'omattiassiv@google.co.uk', '441-770-5833', '220 Bartillon Way', 'ehow.com', 'technology', 32);
insert into company (name, email, phone, address, url, type, id) values ('Ntags', 'bdrancew@adobe.com', '598-199-0405', '89137 Orin Circle', 'php.net', 'finance', 33);
insert into company (name, email, phone, address, url, type, id) values ('Yodoo', 'kantoniazzix@sakura.ne.jp', '155-990-4661', '241 Buena Vista Hill', 'examiner.com', 'manufacturing', 34);
insert into company (name, email, phone, address, url, type, id) values ('Jaxnation', 'gdumpletony@cocolog-nifty.com', '535-833-6572', '7 Clarendon Avenue', 'hugedomains.com', 'retail', 35);
insert into company (name, email, phone, address, url, type, id) values ('Layo', 'mdumphreyz@arstechnica.com', '408-113-3007', '59 Lunder Road', 'google.de', 'finance', 36);
insert into company (name, email, phone, address, url, type, id) values ('Skyvu', 'twooland10@meetup.com', '444-637-5911', '3 Mccormick Hill', 'cafepress.com', 'finance', 37);
insert into company (name, email, phone, address, url, type, id) values ('Youfeed', 'ktommis11@mapquest.com', '352-560-5992', '493 Clyde Gallagher Junction', 'zdnet.com', 'finance', 38);
insert into company (name, email, phone, address, url, type, id) values ('Jamia', 'bdade12@loc.gov', '571-528-6386', '24 Valley Edge Drive', 'com.com', 'technology', 39);
insert into company (name, email, phone, address, url, type, id) values ('Roodel', 'rallmark13@blogs.com', '114-760-3311', '87 Heffernan Road', 'yahoo.com', 'technology', 40);
insert into company (name, email, phone, address, url, type, id) values ('Devbug', 'gmahony14@trellian.com', '360-898-9590', '74319 Brentwood Road', 't.co', 'retail', 41);
insert into company (name, email, phone, address, url, type, id) values ('Rooxo', 'zdmitr15@tmall.com', '146-145-7589', '4 Warbler Road', 'adobe.com', 'manufacturing', 42);
insert into company (name, email, phone, address, url, type, id) values ('Voolith', 'mmangan16@canalblog.com', '594-387-4701', '3822 Lakewood Gardens Court', 'google.com.br', 'retail', 43);
insert into company (name, email, phone, address, url, type, id) values ('Babbleblab', 'kcobbe17@technorati.com', '180-354-0745', '96 Fuller Plaza', '163.com', 'technology', 44);
insert into company (name, email, phone, address, url, type, id) values ('Tagcat', 'ogrzegorecki18@goodreads.com', '913-565-8893', '04 Texas Circle', 'exblog.jp', 'healthcare', 45);
insert into company (name, email, phone, address, url, type, id) values ('Minyx', 'aredmayne19@feedburner.com', '401-689-8995', '7212 Mayer Drive', 'ebay.co.uk', 'retail', 46);
insert into company (name, email, phone, address, url, type, id) values ('Fadeo', 'tronca1a@unesco.org', '780-252-0044', '58766 Montana Lane', 'odnoklassniki.ru', 'healthcare', 47);
insert into company (name, email, phone, address, url, type, id) values ('Brightdog', 'achettle1b@eventbrite.com', '226-623-7007', '6930 Hallows Point', 'craigslist.org', 'technology', 48);
insert into company (name, email, phone, address, url, type, id) values ('Tagfeed', 'lgeorg1c@fc2.com', '525-886-9879', '11983 Novick Place', 'mysql.com', 'technology', 49);
insert into company (name, email, phone, address, url, type, id) values ('Ntag', 'jsouness1d@washington.edu', '933-264-4507', '861 Anderson Court', 'eventbrite.com', 'retail', 50);
