insert into internship (id, name, description, url, companyId) values (1, 'Marketing Intern', 'teamwork', 'http://I+\.Q{2,}/-+', 24);
insert into internship (id, name, description, url, companyId) values (2, 'Marketing Intern', 'problem-solving', 'http://www\.-+\.n{2,}\.h{2,}/-+', 23);
insert into internship (id, name, description, url, companyId) values (3, 'Marketing Intern', 'communication skills', 'http://www\.-+\.S{2,}\.O{2,}/-+', 28);
insert into internship (id, name, description, url, companyId) values (4, 'Software Engineering Intern', 'critical thinking', 'https://-+\.k{2,}/1+', 19);
insert into internship (id, name, description, url, companyId) values (5, 'Data Analyst Intern', 'communication skills', 'http://www\.K+\.G{2,}//+', 7);
insert into internship (id, name, description, url, companyId) values (6, 'Graphic Design Intern', 'creativity', 'http://www\.4+\.H{2,}\.a{2,}/_+', 17);
insert into internship (id, name, description, url, companyId) values (7, 'Human Resources Intern', 'problem-solving', 'http://B+\.p{2,}/e+', 30);
insert into internship (id, name, description, url, companyId) values (8, 'Graphic Design Intern', 'analytical skills', 'https://www\.n+\.x{2,}/F+', 20);
insert into internship (id, name, description, url, companyId) values (9, 'Graphic Design Intern', 'problem-solving', 'https://www\.Q+\.g{2,}/w+', 2);
insert into internship (id, name, description, url, companyId) values (10, 'Data Analyst Intern', 'time management', 'http://6+\.h{2,}\.E{2,}//+', 8);
insert into internship (id, name, description, url, companyId) values (11, 'Data Analyst Intern', 'teamwork', 'http://www\.0+\.O{2,}\.K{2,}//+', 13);
insert into internship (id, name, description, url, companyId) values (12, 'Graphic Design Intern', 'critical thinking', 'http://-+\.T{2,}/n+', 13);
insert into internship (id, name, description, url, companyId) values (13, 'Marketing Intern', 'analytical skills', 'http://H+\.V{2,}\.i{2,}/G+', 18);
insert into internship (id, name, description, url, companyId) values (14, 'Graphic Design Intern', 'analytical skills', 'http://S+\.f{2,}\.t{2,}/-+', 14);
insert into internship (id, name, description, url, companyId) values (15, 'Graphic Design Intern', 'adaptability', 'http://-+\.d{2,}//+', 6);
insert into internship (id, name, description, url, companyId) values (16, 'Software Engineering Intern', 'creativity', 'https://a+\.t{2,}\.J{2,}/-+', 11);
insert into internship (id, name, description, url, companyId) values (17, 'Human Resources Intern', 'creativity', 'https://www\.J+\.H{2,}/_+', 9);
insert into internship (id, name, description, url, companyId) values (18, 'Software Engineering Intern', 'adaptability', 'http://-+\.I{2,}//+', 30);
insert into internship (id, name, description, url, companyId) values (19, 'Software Engineering Intern', 'teamwork', 'https://e+\.X{2,}\.o{2,}/-+', 5);
insert into internship (id, name, description, url, companyId) values (20, 'Data Analyst Intern', 'adaptability', 'http://R+\.N{2,}\.g{2,}/-+', 14);
insert into internship (id, name, description, url, companyId) values (21, 'Human Resources Intern', 'adaptability', 'https://z+\.n{2,}//+', 3);
insert into internship (id, name, description, url, companyId) values (22, 'Data Analyst Intern', 'communication skills', 'https://-+\.K{2,}\.e{2,}/H+', 4);
insert into internship (id, name, description, url, companyId) values (23, 'Data Analyst Intern', 'leadership', 'http://2+\.J{2,}\.F{2,}/9+', 23);
insert into internship (id, name, description, url, companyId) values (24, 'Data Analyst Intern', 'communication skills', 'http://www\.-+\.j{2,}\.r{2,}/6+', 6);
insert into internship (id, name, description, url, companyId) values (25, 'Human Resources Intern', 'teamwork', 'http://www\.-+\.z{2,}/c+', 4);
insert into internship (id, name, description, url, companyId) values (26, 'Graphic Design Intern', 'adaptability', 'https://www\.-+\.Z{2,}/0+', 11);
insert into internship (id, name, description, url, companyId) values (27, 'Software Engineering Intern', 'teamwork', 'https://-+\.L{2,}\.x{2,}/-+', 20);
insert into internship (id, name, description, url, companyId) values (28, 'Graphic Design Intern', 'adaptability', 'http://6+\.m{2,}\.Y{2,}/_+', 5);
insert into internship (id, name, description, url, companyId) values (29, 'Software Engineering Intern', 'teamwork', 'https://www\.I+\.p{2,}/_+', 9);
insert into internship (id, name, description, url, companyId) values (30, 'Marketing Intern', 'time management', 'http://www\.C+\.p{2,}/e+', 18);
insert into internship (id, name, description, url, companyId) values (31, 'Human Resources Intern', 'leadership', 'https://4+\.T{2,}/_+', 11);
insert into internship (id, name, description, url, companyId) values (32, 'Graphic Design Intern', 'problem-solving', 'https://t+\.R{2,}\.I{2,}//+', 21);
insert into internship (id, name, description, url, companyId) values (33, 'Data Analyst Intern', 'teamwork', 'http://1+\.O{2,}\.t{2,}/A+', 3);
insert into internship (id, name, description, url, companyId) values (34, 'Human Resources Intern', 'leadership', 'https://www\.3+\.A{2,}/-+', 8);
insert into internship (id, name, description, url, companyId) values (35, 'Data Analyst Intern', 'critical thinking', 'https://www\.-+\.V{2,}/5+', 2);
insert into internship (id, name, description, url, companyId) values (36, 'Human Resources Intern', 'problem-solving', 'https://www\.-+\.d{2,}\.b{2,}/_+', 24);
insert into internship (id, name, description, url, companyId) values (37, 'Data Analyst Intern', 'problem-solving', 'http://www\.5+\.R{2,}\.b{2,}/_+', 25);
insert into internship (id, name, description, url, companyId) values (38, 'Software Engineering Intern', 'attention to detail', 'http://0+\.S{2,}\.U{2,}//+', 30);
insert into internship (id, name, description, url, companyId) values (39, 'Marketing Intern', 'analytical skills', 'https://www\.n+\.O{2,}\.l{2,}//+', 30);
insert into internship (id, name, description, url, companyId) values (40, 'Human Resources Intern', 'teamwork', 'https://www\.N+\.n{2,}\.b{2,}/_+', 25);
insert into internship (id, name, description, url, companyId) values (41, 'Human Resources Intern', 'attention to detail', 'http://5+\.q{2,}/N+', 3);
insert into internship (id, name, description, url, companyId) values (42, 'Software Engineering Intern', 'time management', 'https://-+\.Z{2,}/C+', 26);
insert into internship (id, name, description, url, companyId) values (43, 'Software Engineering Intern', 'adaptability', 'https://www\.3+\.y{2,}/_+', 2);
insert into internship (id, name, description, url, companyId) values (44, 'Marketing Intern', 'problem-solving', 'https://www\.2+\.I{2,}/-+', 10);
insert into internship (id, name, description, url, companyId) values (45, 'Graphic Design Intern', 'problem-solving', 'http://f+\.t{2,}//+', 29);
insert into internship (id, name, description, url, companyId) values (46, 'Software Engineering Intern', 'teamwork', 'https://www\.4+\.t{2,}//+', 6);
insert into internship (id, name, description, url, companyId) values (47, 'Data Analyst Intern', 'time management', 'http://c+\.f{2,}\.T{2,}/y+', 1);
insert into internship (id, name, description, url, companyId) values (48, 'Software Engineering Intern', 'problem-solving', 'https://5+\.L{2,}//+', 20);
insert into internship (id, name, description, url, companyId) values (49, 'Software Engineering Intern', 'communication skills', 'https://www\.b+\.Z{2,}\.J{2,}//+', 16);
insert into internship (id, name, description, url, companyId) values (50, 'Data Analyst Intern', 'teamwork', 'https://-+\.H{2,}//+', 16);
